[general]
pidfile = "burrow.pid"
access-control-allow-origin = "0.0.0.0/0"

[httpserver.default]
address = ":8000"

[logging]
level = "info"
use-localtime = false
use-compression = true

[client-profile.dreams]
client-id = "burrow-dreams"
kafka-version = "2.5.0"

[zookeeper]
timeout = 60
root-path = "/burrow"
servers = ["172.172.0.1:2181", "172.172.0.2:2181", "172.172.0.3:2181"]

[cluster.dreams]
class-name = "kafka"
client-profile = "dreams"
topic-refresh = 120
offset-refresh = 30
servers = ["172.172.0.1:9092", "172.172.0.2:9092", "172.172.0.3:9092"]
group-denylist = "^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|kafkaRestToolGroupId.*|fims-integration-tests.*|console-consumer.*)$"

[consumer.dreams]
class-name = "kafka"
cluster = "dreams"
client-profile = "dreams"
servers = ["172.172.0.1:9092", "172.172.0.2:9092", "172.172.0.3:9092"]
#start-latest = true
#backfill-earliest = true
group-denylist = "^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|kafkaRestToolGroupId.*|fims-integration-tests.*|console-consumer.*)$"

[storage.default]
class-name = "inmemory"
workers = 20
intervals = 10
expire-group = 604800
min-distance = 1
group-denylist = "^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|kafkaRestToolGroupId.*|fims-integration-tests.*|console-consumer.*)$"

[evaluator.default]
class-name = "caching"
allowed-lag = 1

[notifier.slacknotify]
class-name = "http"
interval = 100
threshold = 2
#send-once = true
send-close = true
template-open = 'templates/default-slack-post.tmpl'
template-close = 'templates/default-slack-delete.tmpl'
url-open = 'xxx'
url-close = 'xxx'
group-denylist = "^([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|kafkaRestToolGroupId.*|fims-integration-tests.*|console-consumer.*)$"
